# Site settings

title : sometitle
tagline: Lisp, Logic & JavaScript
author :
  name : Dmitry Groshev
  email: lambdadmitry@gmail.com
  github : si14
  twitter : lambdadmitry
email: lambdadmitry@gmail.com

description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "https://si14.github.io"
twitter_username: lambdadmitry
github_username:  si14

# Build settings
markdown: kramdown
kramdown:
  input: GFM

permalink: pretty
